<?php
/**
 * Auto-registers every block in build/blocks/<name>/.
 *
 * @package Pediment
 */

if ( ! defined( 'ABSPATH' ) ) {
	exit;
}

add_filter(
	'block_categories_all',
	function ( array $categories ) {
		array_unshift(
			$categories,
			array(
				'slug'  => 'pediment',
				'title' => __( 'Pediment blocks', 'pediment' ),
			)
		);
		return $categories;
	}
);

/**
 * Register every block in `build/blocks/`. Uses the WP 6.7 manifest-collection API
 * (one PHP require) instead of a per-request filesystem walk + block.json parse.
 * The manifest is generated by `wp-scripts build-blocks-manifest` as part of the
 * build script — see package.json.
 *
 * @param string|null $base_dir Directory containing block subfolders. Defaults to theme's build/blocks.
 */
function pediment_register_blocks( $base_dir = null ) {
	if ( null === $base_dir || '' === $base_dir ) {
		$base_dir = PEDIMENT_THEME_DIR . '/build/blocks';
	}

	if ( ! is_dir( $base_dir ) ) {
		return;
	}

	$manifest = dirname( $base_dir ) . '/blocks-manifest.php';
	if ( function_exists( 'wp_register_block_metadata_collection' ) && file_exists( $manifest ) ) {
		wp_register_block_metadata_collection( $base_dir, $manifest );
	}

	$registry = WP_Block_Type_Registry::get_instance();
	foreach ( glob( $base_dir . '/*', GLOB_ONLYDIR ) as $block_dir ) {
		$block_json = $block_dir . '/block.json';
		if ( ! file_exists( $block_json ) ) {
			continue;
		}
		$meta = json_decode( file_get_contents( $block_json ), true );
		if ( is_array( $meta ) && isset( $meta['name'] ) && $registry->is_registered( $meta['name'] ) ) {
			continue;
		}
		register_block_type( $block_dir );
	}
}

add_action(
	'init',
	function () {
		pediment_register_blocks();
	}
);
