#!/usr/bin/env bash
# Regenerates assets/icons/phosphor-icons.{php,json} from Phosphor core
# (regular weight, MIT). Run manually when bumping the Phosphor version.
set -euo pipefail

VER="2.1.1"
OUT_PHP="assets/icons/phosphor-icons.php"
OUT_JSON="assets/icons/phosphor-icons.json"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "Downloading @phosphor-icons/core@${VER} via npm pack…"
( cd "$tmp" && npm pack "@phosphor-icons/core@${VER}" >/dev/null )
tar -xzf "$tmp"/*.tgz -C "$tmp"

src="$tmp/package/assets/regular"
if [ ! -d "$src" ]; then
  echo "✗ expected directory not found: $src" >&2
  exit 1
fi

php_body=""
json_body=""
first=1
count=0
for f in "$src"/*.svg; do
  slug="$(basename "$f" .svg)"
  # Extract the inner markup (everything between the outer <svg …> and </svg>).
  inner="$(tr -d '\n' < "$f" | sed -E 's#.*<svg[^>]*>(.*)</svg>.*#\1#')"
  # PHP single-quoted string: escape backslashes then single quotes.
  php_esc="${inner//\\/\\\\}"
  php_esc="${php_esc//\'/\\\'}"
  php_body+=$'\t'"'${slug}' => '${php_esc}',"$'\n'
  # JSON string: escape backslashes then double quotes.
  json_esc="${inner//\\/\\\\}"
  json_esc="${json_esc//\"/\\\"}"
  if [ "$first" -eq 1 ]; then first=0; else json_body+=","; fi
  json_body+="\"${slug}\":\"${json_esc}\""
  count=$((count + 1))
done

{
  printf '<?php\n'
  printf '// Generated by tools/build-phosphor-data.sh from @phosphor-icons/core@%s. Do not edit.\n' "$VER"
  printf 'return array(\n'
  printf '%s' "$php_body"
  printf ");\n"
} > "$OUT_PHP"

printf '{%s}\n' "$json_body" > "$OUT_JSON"

echo "wrote $OUT_PHP and $OUT_JSON ($count icons, $(wc -c < "$OUT_JSON") JSON bytes)"
