#!/usr/bin/env bash
# Reference builder for the icon-set data contract. Regenerates four committed
# files under assets/icons/ from Phosphor core (regular weight, MIT):
#
#   icon-markup.php   — return array( 'slug' => '<inner svg>' ); read by PHP render
#   icon-markup.json  — { "slug": "<inner svg>" };            read by the editor grid
#   icon-meta.json    — { "slug": { "c": [cats], "t": [tags] } };  OPTIONAL (search + categories)
#   icon-set.json     — { name, version, viewBox, svgAttrs, license };  render manifest
#
# To swap icon sets: write a builder that emits these four files in these shapes.
# No theme code changes are needed — pediment_icon() and the IconPicker read only
# this contract. icon-meta.json is optional (the picker degrades to slug-only
# search with no category filter when it is absent). svgAttrs must carry every
# presentation attribute the wrapper <svg> needs (fill for filled sets;
# stroke/stroke-width/… for stroke sets like Lucide).
#
# Run manually when bumping the Phosphor version or swapping the set.
set -euo pipefail

VER="2.1.1"
OUT_PHP="assets/icons/icon-markup.php"
OUT_JSON="assets/icons/icon-markup.json"
OUT_META="assets/icons/icon-meta.json"
OUT_SET="assets/icons/icon-set.json"

tmp="$(mktemp -d)"
trap 'rm -rf "$tmp"' EXIT

echo "Downloading @phosphor-icons/core@${VER} via npm pack…"
( cd "$tmp" && npm pack "@phosphor-icons/core@${VER}" >/dev/null )
tar -xzf "$tmp"/*.tgz -C "$tmp"

src="$tmp/package/assets/regular"
if [ ! -d "$src" ]; then
  echo "✗ expected directory not found: $src" >&2
  exit 1
fi

php_body=""
json_body=""
first=1
count=0
for f in "$src"/*.svg; do
  slug="$(basename "$f" .svg)"
  # Extract the inner markup (everything between the outer <svg …> and </svg>).
  inner="$(tr -d '\n' < "$f" | sed -E 's#.*<svg[^>]*>(.*)</svg>.*#\1#')"
  # PHP single-quoted string: escape backslashes then single quotes.
  php_esc="${inner//\\/\\\\}"
  php_esc="${php_esc//\'/\\\'}"
  php_body+=$'\t'"'${slug}' => '${php_esc}',"$'\n'
  # JSON string: escape backslashes then double quotes.
  json_esc="${inner//\\/\\\\}"
  json_esc="${json_esc//\"/\\\"}"
  if [ "$first" -eq 1 ]; then first=0; else json_body+=","; fi
  json_body+="\"${slug}\":\"${json_esc}\""
  count=$((count + 1))
done

{
  printf '<?php\n'
  printf '// Generated by tools/build-phosphor-data.sh from @phosphor-icons/core@%s. Do not edit.\n' "$VER"
  printf 'return array(\n'
  printf '%s' "$php_body"
  printf ");\n"
} > "$OUT_PHP"

printf '{%s}\n' "$json_body" > "$OUT_JSON"

echo "Extracting category/tag metadata…"
node tools/extract-icon-meta.mjs "$tmp/package" "$src" > "$OUT_META"

cat > "$OUT_SET" <<JSON
{"name":"phosphor","version":"${VER}","viewBox":"0 0 256 256","svgAttrs":{"fill":"currentColor"},"license":"MIT"}
JSON

echo "wrote $OUT_PHP, $OUT_JSON, $OUT_META, $OUT_SET ($count icons)"
